# -*- coding: utf-8 -*-
"""hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qPeyhxxZhPiqwq5ZpvaDfDFe0ClDPrm
"""

# =====================================================
# CodeAlpha Internship
# Task 1: Hangman Game
# Developed by: Imran Ali Memon
# Description:
# A simple text-based Hangman game where the player
# guesses letters to find the hidden word.
# =====================================================

import random

# ----------------------------
# List of predefined words
# ----------------------------
word_list = [
    "python",
    "computer",
    "developer",
    "programming",
    "keyboard"
]

# Randomly choose one word
secret_word = random.choice(word_list)

# Create hidden word with underscores
guessed_word = ["_"] * len(secret_word)

# Store guessed letters
guessed_letters = []

# Maximum wrong attempts
attempts_left = 6

print("=" * 50)
print("        WELCOME TO HANGMAN GAME")
print("=" * 50)

# ----------------------------
# Main Game Loop
# ----------------------------
while attempts_left > 0:

    print("\nWord: ", " ".join(guessed_word))
    print("Guessed Letters:", guessed_letters)
    print("Attempts Left:", attempts_left)

    guess = input("Enter a letter: ").lower()

    # Check valid input
    if len(guess) != 1 or not guess.isalpha():
        print("Please enter only ONE alphabet letter.")
        continue

    # Check duplicate guess
    if guess in guessed_letters:
        print("You already guessed this letter.")
        continue

    guessed_letters.append(guess)

    # Correct Guess
    if guess in secret_word:

        print("Correct Guess!")

        for index in range(len(secret_word)):
            if secret_word[index] == guess:
                guessed_word[index] = guess

    else:
        print("Wrong Guess!")
        attempts_left -= 1

    # Check Win
    if "_" not in guessed_word:
        print("\nCongratulations!")
        print("You guessed the word:", secret_word)
        break

# ----------------------------
# Game Over
# ----------------------------
if "_" in guessed_word:
    print("\nGame Over!")
    print("The correct word was:", secret_word)

print("\nThank you for playing!")
